### ISSUE TITLE
Filtering capabilities with extra fields

### ISSUE THREAD

**Issue by pulsarinformatique** [joomla-projects/joomla-cms#270]
Hi

As written on https://github.com/joomla-projects/custom-fields/issues/169 would it be possible to allow Joomla blog / lists views to be filtered and ordered with extra fields ?

Either with the new custom fields addon or with the  more developper oriented method described [here](https://docs.joomla.org/Adding_custom_fields_to_core_components_using_a_plugin) the issue remains the same: Once we have fields they are almost useless until we can use them to filter and order lists.

Of course we could use CCKs and third party extensions (we have been using Seblod for years) but my purpose here is to allow native Joomla lists to be more open and flexible with native Joomla articles (even with custom fields).

I don't want a native cck yet (it may come after) but only a comprehensive way to define custom fields and above all to be able to use them really (not only displaying them).

thanks

cyril

**Comment by wilsonge** [comment]
Let's have this conversation in one place in https://github.com/joomla-projects/custom-fields/issues/169

**Comment by laoneo** [comment]
I guess pulsar wanted to post it here https://github.com/joomla/joomla-cms. Is it possible to move issue to the cms repo? If not, can you please open a new one on the main cms repo?

**Comment by laoneo** [comment]
And please don't ask for custom fields filter and sorting, but more for the default fields of articles.
